// <auto-generated />
using System;
using CLOTHES_PROJECT.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CLOTHES_PROJECT.Migrations
{
    [DbContext(typeof(Clothes_Context))]
    partial class Clothes_ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CLOTHES_PROJECT.Models.Department", b =>
                {
                    b.Property<int>("DNUMBER")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DNUMBER"));

                    b.Property<string>("DLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MGRSSN")
                        .HasColumnType("int");

                    b.Property<DateTime>("MGRStartDate")
                        .HasColumnType("Date");

                    b.HasKey("DNUMBER");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("CLOTHES_PROJECT.Models.Dependent", b =>
                {
                    b.Property<int>("ESSN")
                        .HasColumnType("int");

                    b.Property<string>("Dependent_Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Bdate")
                        .HasColumnType("Date");

                    b.Property<string>("Relationship")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("ESSN", "Dependent_Name");

                    b.HasIndex("ESSN")
                        .IsUnique();

                    b.ToTable("Dependents");
                });

            modelBuilder.Entity("CLOTHES_PROJECT.Models.Employee", b =>
                {
                    b.Property<int>("SSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SSN"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Bdate")
                        .HasColumnType("Date");

                    b.Property<int>("DNUM")
                        .HasColumnType("int");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SUPERSSN")
                        .HasColumnType("int");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("SSN");

                    b.HasIndex("DNUM");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("CLOTHES_PROJECT.Models.Project", b =>
                {
                    b.Property<int>("PNUMBER")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PNUMBER"));

                    b.Property<int>("DNUM")
                        .HasColumnType("int");

                    b.Property<string>("Plocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PNUMBER");

                    b.HasIndex("DNUM");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("CLOTHES_PROJECT.Models.WORKS_ON", b =>
                {
                    b.Property<int>("ESSN")
                        .HasColumnType("int");

                    b.Property<int>("PNO")
                        .HasColumnType("int");

                    b.Property<int>("Hours")
                        .HasColumnType("int");

                    b.HasKey("ESSN", "PNO");

                    b.HasIndex("PNO");

                    b.ToTable("WORKS_ON");
                });

            modelBuilder.Entity("CLOTHES_PROJECT.Models.Dependent", b =>
                {
                    b.HasOne("CLOTHES_PROJECT.Models.Employee", "Employee")
                        .WithOne("Dependent")
                        .HasForeignKey("CLOTHES_PROJECT.Models.Dependent", "ESSN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("CLOTHES_PROJECT.Models.Employee", b =>
                {
                    b.HasOne("CLOTHES_PROJECT.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DNUM")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CLOTHES_PROJECT.Models.Project", b =>
                {
                    b.HasOne("CLOTHES_PROJECT.Models.Department", "Department")
                        .WithMany("Projects")
                        .HasForeignKey("DNUM")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CLOTHES_PROJECT.Models.WORKS_ON", b =>
                {
                    b.HasOne("CLOTHES_PROJECT.Models.Employee", "Employee")
                        .WithMany("WORKS_ONs")
                        .HasForeignKey("ESSN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CLOTHES_PROJECT.Models.Project", "Project")
                        .WithMany("WORKS_ONs")
                        .HasForeignKey("PNO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("CLOTHES_PROJECT.Models.Department", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("CLOTHES_PROJECT.Models.Employee", b =>
                {
                    b.Navigation("Dependent");

                    b.Navigation("WORKS_ONs");
                });

            modelBuilder.Entity("CLOTHES_PROJECT.Models.Project", b =>
                {
                    b.Navigation("WORKS_ONs");
                });
#pragma warning restore 612, 618
        }
    }
}
